# henhouse.toml: config file for henhouse
# Please check all values before running henhouse.

log_file = "/home/ubuntu/henhouse_logs/henhouse.log"

# Path to directory contains task xml files
task_dir = "/home/ubuntu/go/src/github.com/jollheef/henhouse/config/tasks/"

[Database]
connection = "user=henhouse password=STRENGTH_PASSWORD dbname=henhouse sslmode=disable"
max_connections = 90 # should be less than same value in postgresql.conf
safe_reinit = false # disallow reinit after game start

[Scoreboard]
www_path = "/home/ubuntu/go/src/github.com/jollheef/henhouse/scoreboard/www"
template_path = "/home/ubuntu/go/src/github.com/jollheef/henhouse/scoreboard/templates"
addr = ":8000"
recalc_timeout = "1m"

[WebsocketTimeout]
info = "1s"
scoreboard = "10s"
tasks = "10s"

[TaskPrice]
# use non linear function for calculate teams base
use_non_linear = false
# for correct work with small amount of teams
use_teams_base = false
teams_base = 20
# 500 if percent of solve less than value
p500 = 10
p400 = 15
p300 = 30
# 200 if percent of solve less than value
p200 = 50
# other 100

[Game]
# Europe/Moscow
start = "Dec 18 00:00 2017"
end = "Dec 18 23:59 2017"

[Flag]
# timeout between send flags
send_timeout = "1s"

[Task]
# timeout after send correct flag before open next task
open_timeout = "1s"
# auto open task after previous solved
auto_open = true
auto_open_timeout = "1h"

[[Teams]]
name = "FooTeam"
description = "Foo test team"
token = "33"

[[Teams]]
name = "BarTeam"
description = "Bar test team"
token = "22"

[[Teams]]
name = "Admin"
test = true
token = "11"
